### ISSUE TITLE
Contract Ownership is detecting unrelated Contracts

### ISSUE THREAD

**Issue by seaona** [409H/eoa-migrator#2]
**Summary**: the application is detecting some contracts that are not related to the connected account. Neither is the contract creator or is the owner of this contracts.

**Connected account:** '0x07Be9763a718C0539017E2Ab6fC42853b4aEeb6B'

**Application is pointing to:**
- Polygon:
  - https://polygonscan.com/address//0x3aFe99bd92b1aed3237196B26743681766D4940E
  - https://polygonscan.com/address//0xC60Ca833Aef1911c17d4E69fDa9de6850402f6E5

![image](https://user-images.githubusercontent.com/54408225/158430678-c7913f6b-b551-40ac-94e0-2dbdb3162d5d.png)
- Mainnet:

  - https://etherscan.io/address//0x0903a9C5e3Fc0CF93488b4D8Eb041a2C446d8A4a
![image](https://user-images.githubusercontent.com/54408225/158433439-90fe92d7-01a6-4a0d-a84b-0b4d094483eb.png)

**Comment by 409H** [comment]
Thanks! This is a mistake on my part - I did not remove the hardcoded address. Fixed in https://github.com/409H/eoa-migrator/pull/3

**Comment by seaona** [comment]
Great, will test this part again when it's merged
